// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUmkM8v5yNP3c87L89aqKs1yQI4G9CEsw',
    appId: '1:191274796779:web:538746318370a5a9bea0ae',
    messagingSenderId: '191274796779',
    projectId: 'mourad-project-f9e60',
    authDomain: 'mourad-project-f9e60.firebaseapp.com',
    storageBucket: 'mourad-project-f9e60.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0gMmYRQ0I7mXzSgLsUPsH0HFYv9s8JAs',
    appId: '1:191274796779:android:f76d083589fe58e9bea0ae',
    messagingSenderId: '191274796779',
    projectId: 'mourad-project-f9e60',
    storageBucket: 'mourad-project-f9e60.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpg_vL0gh0D28qxIrxYZ3klp09tNWCKdA',
    appId: '1:191274796779:ios:447acc9175781c19bea0ae',
    messagingSenderId: '191274796779',
    projectId: 'mourad-project-f9e60',
    storageBucket: 'mourad-project-f9e60.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppAcade',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpg_vL0gh0D28qxIrxYZ3klp09tNWCKdA',
    appId: '1:191274796779:ios:447acc9175781c19bea0ae',
    messagingSenderId: '191274796779',
    projectId: 'mourad-project-f9e60',
    storageBucket: 'mourad-project-f9e60.firebasestorage.app',
    iosBundleId: 'com.example.flutterAppAcade',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAUmkM8v5yNP3c87L89aqKs1yQI4G9CEsw',
    appId: '1:191274796779:web:6424ba8dba24fd6ebea0ae',
    messagingSenderId: '191274796779',
    projectId: 'mourad-project-f9e60',
    authDomain: 'mourad-project-f9e60.firebaseapp.com',
    storageBucket: 'mourad-project-f9e60.firebasestorage.app',
  );

}